services:
  - type: web
    name: savdo24-marketplace
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm run start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: ENCRYPTION_KEY
        generateValue: true
      - key: COINGATE_API_TOKEN
        sync: false
      - key: CONTABO_S3_ENDPOINT
        sync: false
      - key: CONTABO_ACCESS_KEY
        sync: false
      - key: CONTABO_SECRET_KEY
        sync: false
      - key: CONTABO_BUCKET_NAME
        sync: false
      - key: CDN_DOMAIN
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_STORAGE_CHANNEL_ID
        sync: false
      - key: TELEGRAM_BOT_INTERNAL_SECRET
        sync: false
      - key: TELEGRAM_BACKUP_CHAT_ID
        sync: false
      - key: BACKUP_GITHUB_TOKEN
        sync: false
      - key: BACKUP_GITHUB_REPO
        sync: false
      - key: BACKUP_GITHUB_EMAIL
        sync: false
      - key: BACKUP_GITHUB_NAME
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: VITE_GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: APP_URL
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: SMTP_SERVICE
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: TELEGRAM_ADMIN_CHAT_ID
        sync: false
