name: Savdo24 Continuous Integration

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run Prisma Client Generation
        run: |
          npx prisma generate --schema=prisma/schema.sqlite.prisma
          npx prisma generate --schema=prisma/schema.prisma

      - name: Run TypeScript validation
        run: npx tsc --noEmit

      - name: Build Application
        run: npm run build
