name: Deploy to Contabo

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          # key: ${{ secrets.VPS_SSH_KEY }} # Agar SSH kalit ishlatsangiz, buni yoqing va parolni o'chiring
          port: 22
          script: |
            cd /path/to/your/project # DIQQAT: Bu yerni loyihangiz papkasiga o'zgartiring! (masalan: cd /var/www/savdo24)
            chmod +x deploy.sh
            ./deploy.sh
